[package]
name = "cs452"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aarch64-cpu = "9.4.0"
lock_api = "0.4.11"
tock-registers = "0.9.0"

[[bin]]
name = "kernel"
path = "src/main.rs"
