[package]
name = "lunaris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aarch64-cpu = "9.4.0"
panic-halt = "0.2.0"
tock-registers = "0.9.0"

[profile.release]
lto = true
