[package]
name = "lunaris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aarch64-cpu = "9.4.0"
panic-halt = "0.2.0"
ringbuf = { version = "0.3.3", default-features = false}
tock-registers = "0.9.0"

[profile.release]
lto = true
strip = true

[[bin]]
name = "lunaris"
test = false
bench = false

[features]
default = []
lab = []
