[tasks.image]
command = "rust-objcopy"
args = ["--strip-all", "-O", "binary", "target/aarch64-unknown-none/${@}/lunaris", "kernel.img"]
dependencies = ["build"]

[tasks.image-lab]
command = "rust-objcopy"
args = ["--strip-all", "-O", "binary", "target/aarch64-unknown-none/${@}/lunaris", "kernel.img"]
dependencies = ["build-lab"]

[tasks.build]
command = "cargo"
args = ["build", "--${@}"]

[tasks.cleanup]
command = "rm"
args = ["-rf", "kernel.img"]

[tasks.build-lab]
command = "cargo"
args = ["build", "--${@}", "--features", "lab", "--no-default-features"]

[tasks.qemu]
command = "qemu-system-aarch64"
args = ["-M", "raspi3b", "-m", "1024", "-serial", "mon:stdio", "-nographic", "-kernel", "kernel.img"]
dependencies = ["image"]
