[tasks.image]
command = "rust-objcopy"
args = ["--strip-all", "-O", "binary", "target/aarch64-unknown-none/${@}/lunaris", "kernel.img"]
dependencies = ["build"]

[tasks.build]
command = "cargo"
args = ["build", "--${@}"]

[tasks.run-qemu]
command = "qemu-system-aarch64"
args = ["-M", "raspi3b", "-m", "1024", "-serial", "mon:stdio", "-nographic", "-kernel", "kernel.img"]
